name: bulletin
description: A flutter package to show fully customizable multiple animating flash cards
version: 0.0.1
repository: https://github.com/DevsOnFlutter/bulletin

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
